= Chapter5

== 01. Objects, Instance Methods, and Instance Variables

- Dynamic <-> Static
- class variable, class method (static)
- instance variable, instance method (non-static)
- 클래스의 소스 코드와 (메모리 내의) 클래스 자체를 구별해야 한다는 점에 유의하라. 소스 코드는 클래스와 해당 클래스에서 생성된 객체를 모두 결정한다.
- static과 non-static 멤버가 혼합된 클래스의 예는 손에 꼽는다.
- 즉, 대부분의 클래스는 static 멤버만 포함하거나 non-static 멤버만 포함한다.
- 변수는 객체 자체를 보유하는 대신, 메모리에서 객체를 찾는 데 필요한 정보를 보유한다. 이러한 정보를 객체에 대한 참조(reference) 또는 포인터(pointer)라고 한다.
[source, java]
----
Student std = new Student();
----
- 위에서 new 연산자는 객체를 생성하고 해당 객체에 대한 참조를 반환한다. (new 연산자는 클래스에서 생성자라고 불리는 특별한 서브루틴을 호출한다.)
[source, java]
----
std = null;
----
- 이렇게 하면 std는 null을 가리키는 것이 아닌 변수 std는 null이다.
- 하나의 객체 변수가 다른 것에 할당될 때, 오로지 참조만이 복사된다. 참조된 객체가 복사되는 것이 아니다.

== 02. Constructors and Object Initialization

- 생성자 내부를 제외하면 final 인스턴스 변수에 값을 할당하는 것은 허용되지 않는다.
- dangling2 pointer error, memory leak

== 03. Programming with Objects

- 잘 설계된 클래스는 편집 없이도 재사용할 수 있는 소프트웨어 구성요소이다.
-  우수한 설계의 수용 원칙을 사용하는 프로그래밍에 대한 체계적인 접근 방식을 소프트웨어 엔지니어링(software engineering)이라고 한다.

== 04. Programming Example: Card, Hand, Deck

- 모든 해당 인스턴스 변수가 final이면 해당 객체는 불변적인(immutable) 객체다.

== 05. Inheritance, Polymorphism, and Abstract Classes

- ClassCastException은 참조하는 객체의 실제 유형이 은 컴파일될 때 알 수 없기 때문에 런타임에 발생한다.

[source, java]
----
if (myVehicle instanceof Car myCar) {
    System.out.println("Type of vehicle: Car");
    System.out.println("Number of doors: " + myCar.numberOfDoors);
}
----
- method가 수행하는 동작이 run-time에 method 적용되는 object의 type에 따라 달라지는 경우 method는 polymorphic하다.
- Polymorphism just means that different objects can respond to the same message in different ways.

[source, java]
----
void setColor(Color newColor) {
   color = newColor; // change value of instance variable
   redraw(); // redraw shape, which will appear in new color
}
----
- A class that is not abstract is said to be concrete
- 클래스가 final class로 정의된 경우 sub class를 가질 수 없다.
- method가 final로 정의된 경우 method overriding을 할 수 없다.

== 06. this and super

== 07. Interfaces
- Interface는 다중 상속과 동일한 목표롤 달성하는 데 사용할 수 있다.
- Interface는 구현 없이 a set of instance method interfaces로 구성된다.
- Interface는 object를 생성할 수 없지만, Interface에 의해 유형이 지정된 변수를 선언할 수 있습니다.

=== systax rules for Interface
- Interface는 implements 하는 수에 제한이 없음.
- Interface는 abstrat method만 포함하는 pure한 abstract class와 같다.
- Interface에 선언된 method는 public or abstract여야 한다.
- Interface에 변수 선언도 포함될 수 있다. public static final이어야 하며, 모든 변수는 상수이다.
- Interface는 하나 이상의 Interface를 extends 할 수 있다.

=== semantic rules for Interface
- 인터페이스 정의에는 해당 의미를 표현하는 주석이 포함되어야 한다.
- 인터페이스를 구현하는 클래스는 해당 의미 를 고려해야 한다.

== 08. Nested Classes
- nested class가 포함 클래스의 인스턴스 변수나 인스턴스 메서드를 사용해야 하는 경우 중첩 클래스를 non-static으로 만듭니다. 그렇지 않으면 static일 수도 있습니다.
- 대부분의 경우 inner class는 해당 클래스가 정의된 클래스 내에서만 사용됩니다.
- Anonymous Inner Classes : run-time에 해당 클래스에 속하는 object를 만든다.
- innerclass를 가진 파일을 컴파일 하면 containing class와 inner클래스 각각 .class 파일이 만들어진다. innerclass의 이름은 {containingclass-name}${innerclass-name}.class

=== Inner class
- Inner class는 non-static으로 선언된 nested class를 말한다.
- Inner class는 static member를 가질 수 없다.
- 

=== Local class
- Local class : subroutine 정의 내에서 정의된 class
- local class는 해당 클래스가 정의된 서브루틴 내에서만 사용할 수 있습니다. 그러나 local class에 의해 정의된 object는 해당 서브루틴 외부에서 사용할 수 있습니다.
- Local class는 해당 클래스가 정의된 subroutine의 지역 변수를 사용할 수 있다. 또한 해당 subroutine의 parameter를 사용할 수 있다. 
- 그러나 이러한 경우 제한이 있다. local variable, parameter는 final로 선언되어야 하며, 명시적으로 final이 선언되지 않은 경우 실질적으로 final이어야 한다.
- lambda expression

[source, java]
----
FunctionR2R[] multipliers = new FunctionR2R[100];
for (int i = 0; i < 100; i++) {
   int n = i;
   multipliers[i] =  z -> n * z;
}
----
- anonymous class

[source, java]
----
FunctionR2R[] multipliers = new FunctionR2R[100];
for (int i = 0; i < 100; i++) {
   int n = i;
   multipliers[i] =  new FunctionR2R() {
       public double valueAt(double x) {
          return n * x;
       }
   };
}
----