= Chapter8

buffer overflow error::
버퍼에 수용할 수 있는것보다 더 많은 데이터를 받았을때 발생

* 자바는 numerical computation에 대해서는 자동으로 오류를 감지하지 않는다.
[source]
----
int number = Integer.MAX_VALUE + 1;
// Integer.MIN_VALUE의 값이 나온다.
----

state::
프로그램 실행 중 특정 순간의 프로그램 실행과 관련된 모든 정보로 구성된다.

process::
컴퓨터가 프로그램을 실행할 때 거치는 일련의 state

* 프로그램 문장의 의미는 문장이 컴퓨터의 상태에 미치는 영향.

PostConditions::
프로그램이 실행된 후에 참이라고 입증될 수 있는 사실.

PreConditions::
프로그램이 올바르게 동작하기 위해 만족해야하는 조건

Invariant::
* loop invariant : 루프가 실행되는 동안 항상 참인 문장
** 루프 코드가 실행되기 전의 문장이 참이라면, 루프 코드가 실행된 이후에도 해당 문장은 참이어야 한다.
** loop invariant는 루프에 대한 precondition, postcondition 둘 다 해당한다.

[source]
----
static int arraySum(int[] A) {
    int total = 0;
    int i = 0
    while (i < A.length) {
        total = total + A[i]; 
        i++;
    }

    return total;
}
----

* loop invariant는 loop 내부에서 항상 참일 필요는 없다.

[source]
----
static int maxInArray( int[] A ) {
    int max = A[0];
    int i = 1;
    while ( i < A.length ) {
        if ( A[i] > max )
            max = A[i];
        i = i + 1;
    }
    return max;
}
----
* loop invariant : max는 A의 처음부터 i번째의 요소들 중에서 가장 큰 값이다.

class invariant::
클래스나 클래스에서 생성된 객체에 대해서 항상 참이어야 하는 statement

* class invariant는 일반적으로 생성자에 대한 postcondition이고,
class의 모든 메소드들에 대한 postcondition, precondition이다.

Error::
합리적인 처리 방법이 없기 때문에 일반적으로는 프로그램 종료를 초래하는 심각한 오류

Exception::
포착되어 처리해야하는 예외.

try...catch::
* catch : exception handler

[source]
----
try {
    statement
} 
optional-catch-clauses
optional-finally-caluse // 예외 발생 여부와 관계없이 항상 실행 되는 문장
----

checked exception::
반드시 처리 되어야 하는 예외. 컴파일러가 처리 되는지 확인한다.

efficiency(효율성)::
시간, 메모리, 저장 공간 등 모든 자원을 효율적으로 사용하는 것.

== **Analysis of Algorithm**

* Big-Oh
알고리즘이 실행되는 최대 시간 (상한)

* Big-Omega
알고리즘이 실행되는 최소 시간 (하한)

* Big-Theta
알고림즘이 실행되는 평균 시간

