= Chapter 7 Arrays, ArrayLists, and Records

== 01. Array Details

[source, java]
----
int[] arr = new int[10];
for (int x : arr) {
    x = 1;
}
----

- for-each loop는 array의 value를 제공하기 때문에 위와 같은 할당문은 제대로 값이 할당되지 않는다.(배열의 주소가 아닌 주소의 값을 가져옴)
- fixed arity method, variable arity method
- variable arity method ex)

[source, java]
----
public static double average( double...  numbers ) {
----

- 위와 같은 average 함수에 double number를 여개 넣고 호출하면, number들은 double array에 담겨서 넘겨진다.
- ...은 subroutine 선언에서 parameter들 중 제일 마지막에 써야 한다.
- Array Literals
[source, java]
----
int[] squares = { 1, 4, 9, 16, 25, 36, 49 };

cubes = new int[] { 1, 8, 27, 64, 125, 216, 343 };
----

== 02. Array Proccesing

== 03. Wrapper class

- autoboxing : 아래 첫 번째 줄과 같이 작성했을 때 컴퓨터는 이를 밑에 처럼 읽게 만든다.

[source, java]
----
Integer answer = 42;

Integer answer = Integer.valueOf(42);
----

- unboxing : autoboxing이 반대로 적용되는 것.

== 04. Records

- array는 number로 indexing 하는 반면 record는 name으로 indexing 한다.
- Java에서의 레코드는 다른 programming language들의 레코드와는 다르게 한 번 생성되면 수정할 수 없다.
[source, java]
----
public record FullName(String firstName, String lastName) { }
----
- Java에서의 레코드 definition
- canonical constructor : 컴파일러에 의해 자동으로 제공된다.

[source, java]
----
public final class FullName {
    private final String firstName;
    private final String lastName;
    public FullName( String firstName, String lastName ) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public firstName() {
        return firstName;
    }
    public lastName() {
        return lastName;
    }
    public String toString() {
       return "FullName[firstName=" + firstName 
                      + ", lastName=" + lastName + "]";
    }
    public boolean equals(Object obj) {
        // (definition omitted)
    }
    public int hashCode() {
        // (definition omitted)
    }
}
----
- record 선언문은 위와 같은 의미이다. Record는 자동으로 final이 된다. 이는 sub class를 가질 수 없다는 의미이다. record는 object의 sub class이다.
- record의 getter는 getXXX 보다 instance value 이름 그대로를 쓰는 편이다.
- record class를 nested class로 사용할 경우 굳이 static으로 선언하지 않아도 된다. 자동으로 static으로 되기 때문이다.
- record class를 사용하려면 record class로 설계될 데이터가 immutable인지를 고려해야 한다.
- record class는 body {}에 다른 static value나 method 등을 추가할 수 있고, canonical constructor에 추가할 내용 그리고 toString, equals, hashCode 등을 extends 할 수 있다.
- Additional constructors can be defined, but any non-canonical constructor must begin with a call to a constructor in the same class, using the special variable this
- record가 final, immutable인 이유 : One reason for them to be final is that it can make it possible for a complier to apply certain kinds of optimization to the code that it generates. This applies not just to record classes but to final classes in general.

== 05. Searching and Sorting

- Association lists : (w, d), w = word, d = definition 값의 쌍들을 저장함.
- InsertionSort : 저장하고자 하는 값의 저장 위치를 찾아서 저장
- SelectionSort : 가장 큰 값을 찾아서 맨 뒤에 놓는 작업을 반복

== 06. Tow-dimensional Arrays
