= Chapter 2

== Section 2.1 The Basic Java Application

1. **Syntax** : The rules that determine what is allowed of the language

2. **Semantics** : The meaning of a program. The set of rules that determine the meaning of a program written in that language. +
(Syntax와 Semantics의 차이 : Syntax는 문법. 즉, 언어의 문법(컴파일이 돌아가는지)을 의미하고, Semantics는 프로그램의 코드가 타당한지(의미가 맞는지)를 의미.)

3. **pragmatics** : 화용론? 말하는 사람, 듣는 사람, 시간과 장소 등을 언어 의미 분석의 주요 요소로 삼는, 언어 이론의 한 분야. 일반적인 용어로 style이라고도 함

4. **built-in subroutine** : built-in type의 subrountine이라는 뜻. 미리 만들어져 있는 subroutine

5. **name** : Names are fundamental to programming. According to the syntax rules of Java, the most basic names are identifiers. 

6. **naming** : 클래스 이름은 대문자로 시작하고, 변수 이름과 서브루틴 이름은 소문자로 시작하는 것이 관례이다.

7. **variable** : high-level language에서 데이터를 참조하기 위해 숫자 주소 대신 name이 사용됨. 메모리에 저장된 데이터를 참조(refer)하기 위해 사용되는 이름.

8. **primitive types** : byte, short, int, long, float, double, char, boolean.

8. **subroutines, functions** : 모든 서브루틴은 특정 작업을 수행하지만 일부 서브루틴의 경우 작업은 일부 데이터 값을 계산하거나 검색하는 것입니다. 이러한 유형의 서브루틴을 함수라고 합니다 .



== 단어 정리
convention : 규칙, 관습
oblivious : 감지하지 못하는, 의식이 없는??
paramount : 가장 중요한
